import XCTest

final class PlayerRegressionUITests: XCTestCase {
    private let remote = XCUIRemote.shared

    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    func testPlaybackPauseScrubTracksAndSubtitles() throws {
        // The known episode is H.264 and exposes real subtitle tracks, so
        // CoreSimulator can exercise both seek directions without relying
        // on a just-in-time HEVC transcode playlist.
        let app = launchPlayer(title: "Pilot", series: "Young Sheldon")
        waitForState(in: app, timeout: 45) { value in
            value.int("ready") == 1 && value.int("audioCount") > 0
        }

        let startingTime = state(in: app).double("time")
        waitForState(in: app, timeout: 8) { $0.double("time") > startingTime + 2 }

        remote.press(.playPause)
        waitForState(in: app, timeout: 5) { $0.int("paused") == 1 }
        let pausedTime = state(in: app).double("time")
        Thread.sleep(forTimeInterval: 1.5)
        XCTAssertLessThan(abs(state(in: app).double("time") - pausedTime), 0.8)

        remote.press(.playPause)
        waitForState(in: app, timeout: 5) { $0.int("paused") == 0 }

        let beforeScrub = state(in: app).double("time")
        remote.press(.right)
        waitForState(in: app, timeout: 3) { $0.int("scrubbing") == 1 }
        XCTAssertTrue(app.descendants(matching: .any)["player.scrub.chip"].exists)
        XCTAssertGreaterThan(state(in: app).int("chapters"), 0)
        XCTAssertEqual(state(in: app).int("trickplay"), 1)

        // Keep the scrub open while the authenticated trickplay sheet loads.
        for _ in 0..<4 {
            if state(in: app).int("trickplayFrame") == 1 { break }
            Thread.sleep(forTimeInterval: 0.35)
            remote.press(.right)
        }
        waitForState(in: app, timeout: 8) { $0.int("trickplayFrame") == 1 }
        remote.press(.select)
        // A simulator-only HLS rendition may still be generated by the
        // server after the optimistic playhead moves. Wait for the custom
        // engine to re-prime instead of mistaking that work for a bad seek.
        waitForState(in: app, timeout: 30) {
            $0.int("scrubbing") == 0
                && $0.int("buffering") == 0
                && $0.double("time") > beforeScrub + 5
        }

        let afterForwardScrub = state(in: app).double("time")
        remote.press(.left)
        waitForState(in: app, timeout: 3) { $0.int("scrubbing") == 1 }
        remote.press(.select)
        waitForState(in: app, timeout: 30) {
            $0.int("scrubbing") == 0
                && $0.int("buffering") == 0
                && $0.double("time") < afterForwardScrub - 5
        }

        exerciseSubtitles(in: app)
    }

    func testRealAudioTrackSwitchReprimesPlayback() {
        // Resolve a server-declared direct-play H.264 item with multiple
        // embedded renditions. This remains simulator-decodable without
        // hard-coding a private-library title.
        let app = launchPlayer(
            title: "multi-audio-regression",
            extraArguments: ["-debug.regressionFindMultiAudioH264", "YES"]
        )
        waitForState(in: app, timeout: 60) {
            $0.int("ready") == 1 && $0.int("audioCount") > 1
        }
        exerciseAudioTracks(in: app)
    }

    func testAutomaticIntroSkipUsesRealSegmentAndPlayerSeek() throws {
        let app = launchPlayer(
            title: "hardware-regression",
            series: "9-1-1",
            extraArguments: [
                "-debug.regressionFindSkippableEpisode", "YES",
                "-debug.regressionStartAtFirstSkippable", "YES",
                "-playback.skipMode", "autoDelay",
                "-playback.autoplayMode", "off",
            ]
        )
        waitForState(in: app, timeout: 45) {
            $0.int("ready") == 1 && $0.double("skippableEnd") > $0.double("skippableStart")
        }
        let end = state(in: app).double("skippableEnd")
        XCTAssertTrue(app.descendants(matching: .any)["player.skip"].waitForExistence(timeout: 4))
        waitForState(in: app, timeout: 12) { $0.double("time") >= end - 0.75 }
        XCTAssertFalse(app.descendants(matching: .any)["player.skip"].exists)
    }

    func testRealSubtitleCueReachesThePlayerOverlay() {
        let app = launchPlayer(title: "Pilot", series: "Young Sheldon")
        waitForState(in: app, timeout: 45) {
            $0.int("ready") == 1 && $0.int("subtitleCount") > 0 && $0.int("subtitle") > 0
        }
        waitForState(in: app, timeout: 60) { $0.int("subtitleVisible") == 1 }
        XCTAssertTrue(
            app.descendants(matching: .any)["player.subtitle.text"].exists
                || app.descendants(matching: .any)["player.subtitle.image"].exists
        )
    }

    func testTvOSSettingsHierarchyPickersAndHomeRowsNavigation() {
        let app = XCUIApplication()
        app.launchArguments = [
            "-debug.playerRegression", "YES",
            "-debug.regressionBootstrapPublicDemo", "YES",
            "-debug.settingsRegression", "YES",
        ]
        app.launch()

        let settingsTab = app.tabBars.buttons["Settings"]
        XCTAssertTrue(settingsTab.waitForExistence(timeout: 20))
        let homeTab = app.tabBars.buttons["Home"]
        for _ in 0..<8 where !homeTab.hasFocus && !settingsTab.hasFocus {
            remote.press(.up)
            Thread.sleep(forTimeInterval: 0.15)
        }
        moveFocus(to: settingsTab, maxPresses: 10) { remote.press(.right) }
        remote.press(.select)

        let audio = app.descendants(matching: .any)["settings.category.audio"]
        XCTAssertTrue(audio.waitForExistence(timeout: 8))
        moveFocus(to: audio, maxPresses: 5) { remote.press(.down) }
        remote.press(.select)

        let defaultAudio = app.descendants(matching: .any)["settings.audio.default"]
        XCTAssertTrue(defaultAudio.waitForExistence(timeout: 5))
        // SwiftUI exposes a tvOS Menu as an accessibility container rather
        // than as the focused UIButton. The focus engine still moves from
        // the Back button to the first menu row deterministically.
        remote.press(.down)
        remote.press(.select)
        let originalAudio = app.descendants(matching: .any)["Original Audio"]
        XCTAssertTrue(originalAudio.waitForExistence(timeout: 5))
        let previousAudioDefault = defaultAudio.valueDescription
        // Menu items have the same XCTest accessibility quirk as their
        // parent Menu, so validate the selection result rather than a false
        // `hasFocus` reading. tvOS opens this menu on its first item: choose
        // Original, or Preferred when Original is already persisted.
        remote.press(.down)
        if previousAudioDefault.contains("Original Audio") {
            remote.press(.down)
        }
        remote.press(.select)
        Thread.sleep(forTimeInterval: 0.3)
        XCTAssertNotEqual(defaultAudio.valueDescription, previousAudioDefault)

        let back = app.descendants(matching: .any)["settings.detail.back"]
        XCTAssertTrue(back.waitForExistence(timeout: 3))
        moveFocus(to: back, maxPresses: 5) { remote.press(.up) }
        remote.press(.select)

        let subtitles = app.descendants(matching: .any)["settings.category.subtitles"]
        XCTAssertTrue(subtitles.waitForExistence(timeout: 5))
        moveFocus(to: subtitles, maxPresses: 4) { remote.press(.down) }
        remote.press(.select)
        let appearance = app.descendants(matching: .any)["settings.subtitles.appearance"]
        XCTAssertTrue(appearance.waitForExistence(timeout: 5))
        moveFocus(to: appearance, maxPresses: 8) { remote.press(.down) }
        remote.press(.select)
        XCTAssertTrue(app.descendants(matching: .any)["settings.subtitlePreview"].waitForExistence(timeout: 5))
        remote.press(.menu)
        XCTAssertTrue(appearance.waitForExistence(timeout: 5))
        remote.press(.menu)

        let home = app.descendants(matching: .any)["settings.category.home"]
        XCTAssertTrue(home.waitForExistence(timeout: 5))
        moveFocus(to: home, maxPresses: 4) { remote.press(.down) }
        remote.press(.select)
        let myList = app.descendants(matching: .any)["settings.home.row.MyList"]
        XCTAssertTrue(myList.waitForExistence(timeout: 5))
        moveFocus(to: myList, maxPresses: 6) { remote.press(.down) }
        let previousVisibility = myList.valueDescription
        remote.press(.select)
        XCTAssertNotEqual(myList.valueDescription, previousVisibility)
        remote.press(.menu)
        XCTAssertTrue(home.waitForExistence(timeout: 5))
    }

    func testNativeGenreShelfOpensAFilteredLibrary() {
        let app = XCUIApplication()
        app.launchArguments = [
            "-debug.playerRegression", "YES",
            "-debug.regressionBootstrapPublicDemo", "YES",
        ]
        app.launch()

        XCTAssertTrue(app.tabBars.buttons["Home"].waitForExistence(timeout: 20))
        let genreButtons = app.buttons.matching(
            NSPredicate(format: "identifier BEGINSWITH %@", "home.genre.")
        )

        var focusedGenre: XCUIElement?
        for _ in 0..<20 {
            focusedGenre = genreButtons.allElementsBoundByIndex.first(where: \.hasFocus)
            if focusedGenre != nil { break }
            remote.press(.down)
            Thread.sleep(forTimeInterval: 0.25)
        }

        guard let focusedGenre else {
            XCTFail("Could not focus a card in the native Genres shelf")
            return
        }
        let selectedGenre = focusedGenre.label
        let shelfScreenshot = XCTAttachment(screenshot: app.screenshot())
        shelfScreenshot.name = "Native Genres shelf — \(selectedGenre) focused"
        shelfScreenshot.lifetime = .keepAlways
        add(shelfScreenshot)
        remote.press(.select)

        let library = app.descendants(matching: .any)["genre.library"]
        XCTAssertTrue(library.waitForExistence(timeout: 8), "Did not open \(selectedGenre)")
        let populated = NSPredicate(format: "value != '0 items'")
        expectation(for: populated, evaluatedWith: library)
        waitForExpectations(timeout: 20)
    }

    private func moveFocus(
        to element: XCUIElement,
        maxPresses: Int,
        move: () -> Void
    ) {
        for _ in 0..<maxPresses where !element.hasFocus {
            move()
            Thread.sleep(forTimeInterval: 0.15)
        }
        XCTAssertTrue(element.hasFocus, "Could not focus \(element)")
    }

    private func exerciseAudioTracks(in app: XCUIApplication) {
        let original = state(in: app).int("audio")
        let count = state(in: app).int("audioCount")
        guard count > 1 else {
            XCTFail("The audio regression fixture must expose multiple tracks")
            return
        }
        let timeBeforeSwitch = state(in: app).double("time")

        remote.press(.down)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 1 }
        waitForPanelReveal()
        remote.press(.right)
        waitForState(in: app, timeout: 4) { $0.string("tab") == "video" }
        remote.press(.right)
        waitForState(in: app, timeout: 4) { $0.string("tab") == "audio" }
        remote.press(.down) // first audio row
        waitForState(in: app, timeout: 4) { $0.string("focus") == "track-audio-1" }
        let target = original == 1 ? 2 : 1
        if target == 2 {
            remote.press(.down)
            waitForState(in: app, timeout: 4) { $0.string("focus") == "track-audio-2" }
        }
        remote.press(.select)
        waitForState(in: app, timeout: 30) {
            $0.int("audio") == target && $0.int("buffering") == 0
        }
        remote.press(.menu)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 0 }
        waitForState(in: app, timeout: 8) { $0.double("time") > timeBeforeSwitch + 1 }
    }

    private func exerciseSubtitles(in app: XCUIApplication) {
        guard state(in: app).int("subtitleCount") > 0 else {
            XCTFail("The subtitle regression fixture must expose a subtitle track")
            return
        }

        remote.press(.down)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 1 }
        waitForPanelReveal()
        moveRight(toTab: "subtitles", in: app)
        remote.press(.down) // Off
        waitForState(in: app, timeout: 4) { $0.string("focus") == "track-subtitle-off" }
        remote.press(.select)
        waitForState(in: app, timeout: 8) { $0.int("subtitle") == 0 }
        remote.press(.menu)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 0 }
        Thread.sleep(forTimeInterval: 0.2)

        remote.press(.down)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 1 }
        waitForPanelReveal()
        remote.press(.down) // Off
        waitForState(in: app, timeout: 4) { $0.string("focus") == "track-subtitle-off" }
        remote.press(.down) // first real subtitle
        waitForState(in: app, timeout: 4) { $0.string("focus") == "track-subtitle-1" }
        remote.press(.select)
        waitForState(in: app, timeout: 8) { $0.int("subtitle") == 1 }
        remote.press(.menu)
        waitForState(in: app, timeout: 4) { $0.int("panel") == 0 }

        // Verify that a selected track survives the renderer flush/re-prime
        // performed by a real seek. Cue rendering is covered separately.
        let beforeSeek = state(in: app).double("time")
        remote.press(.right)
        waitForState(in: app, timeout: 3) { $0.int("scrubbing") == 1 }
        remote.press(.select)
        waitForState(in: app, timeout: 30) {
            $0.int("scrubbing") == 0
                && $0.int("buffering") == 0
                && $0.int("subtitle") == 1
                && $0.double("time") > beforeSeek + 5
        }
    }

    private func launchPlayer(
        title: String,
        year: Int? = nil,
        series: String? = nil,
        simulatorTranscode: Bool = true,
        extraArguments: [String] = []
    ) -> XCUIApplication {
        let app = XCUIApplication()
        app.launchArguments = [
            "-debug.playerRegression", "YES",
            "-debug.regressionBootstrapPublicDemo", "YES",
            "-debug.benchSearchTerm", title,
            "-debug.playbackHUD", "YES",
            "-debug.matchContent", "YES",
        ]
        if simulatorTranscode {
            app.launchArguments += ["-debug.simulatorTranscode", "YES"]
        }
        if let year {
            app.launchArguments += ["-debug.benchProductionYear", String(year)]
        }
        if let series {
            app.launchArguments += ["-debug.regressionSeriesName", series]
        }
        app.launchArguments += extraArguments
        app.launch()
        return app
    }

    @discardableResult
    private func waitForState(
        in app: XCUIApplication,
        timeout: TimeInterval,
        predicate: (RegressionState) -> Bool
    ) -> RegressionState {
        let deadline = Date().addingTimeInterval(timeout)
        var latest = RegressionState("")
        repeat {
            latest = state(in: app)
            if predicate(latest) { return latest }
            Thread.sleep(forTimeInterval: 0.2)
        } while Date() < deadline
        XCTFail("Timed out waiting for player state. Latest: \(latest.raw)")
        return latest
    }

    private func state(in app: XCUIApplication) -> RegressionState {
        let element = app.descendants(matching: .any)["player.regression.state"]
        guard element.exists else { return RegressionState("") }
        return RegressionState(element.value as? String ?? "")
    }

    private func waitForPanelReveal() {
        // The panel's spring is 400 ms. Focus becomes eligible only once its
        // tabs have entered the visible focus region on physical tvOS.
        Thread.sleep(forTimeInterval: 0.6)
    }

    private func moveRight(toTab target: String, in app: XCUIApplication) {
        for _ in 0..<3 where state(in: app).string("tab") != target {
            remote.press(.right)
            Thread.sleep(forTimeInterval: 0.15)
        }
        waitForState(in: app, timeout: 4) { $0.string("tab") == target }
    }
}

private struct RegressionState {
    let raw: String
    private let values: [String: String]

    init(_ raw: String) {
        self.raw = raw
        values = Dictionary(uniqueKeysWithValues: raw.split(separator: " ").compactMap { token in
            let pair = token.split(separator: "=", maxSplits: 1).map(String.init)
            return pair.count == 2 ? (pair[0], pair[1]) : nil
        })
    }

    func string(_ key: String) -> String { values[key] ?? "" }
    func int(_ key: String) -> Int { Int(values[key] ?? "") ?? -1 }
    func double(_ key: String) -> Double { Double(values[key] ?? "") ?? -1 }
}

private extension XCUIElement {
    var valueDescription: String {
        value as? String ?? ""
    }
}
